batchify 'enable-https' script

diff --git a/src/https/bin/enable-https b/src/https/bin/enable-https
--- a/src/https/bin/enable-https
+++ b/src/https/bin/enable-https
@@ -3,7 +3,7 @@
 # shellcheck source=src/https/utilities/https-utilities
 . "$SNAP/utilities/https-utilities"
 
-COMMAND="nextcloud.enable-https"
+COMMAND="nextcloud-nextbox.enable-https"
 
 print_usage()
 {
@@ -33,79 +33,88 @@ handle_lets_encrypt()
 	extra_params=""
 	dry_run=false
 
-	while getopts ":dth" opt; do
-		case $opt in
-			d)
-				extra_params="$extra_params --dry-run"
-				dry_run=true
-				;;
-			t) extra_params="$extra_params --test-cert";;
-			h)
-				echo "Usage:"
-				echo "    $COMMAND lets-encrypt [-h -t -d]"
-				echo ""
-				echo "    Obtain a certificate from Let's Encrypt and"
-				echo "    automatically keep it up to date."
-				echo ""
-				echo "    -h: Display this help message"
-				echo "    -t: Obtain a test certificate. This is a valid Let's"
-				echo "        Encrypt certificate, but is not signed by a"
-				echo "        recognized CA, so browsers will show a warning."
-				echo "    -d: Dry run: don't actually obtain/install"
-				echo "        certificates from Let's Encrypt, but make sure"
-				echo "        it's possible."
-				exit 0
-				;;
-			\?)
-				echo "Invalid option: -$OPTARG" >&2
-				exit 1
-				;;
-		esac
-	done
+#	while getopts ":dth" opt; do
+#		case $opt in
+#			d)
+#				extra_params="$extra_params --dry-run"
+#				dry_run=true
+#				;;
+#			t) extra_params="$extra_params --test-cert";;
+#			h)
+#				echo "Usage:"
+#				echo "    $COMMAND lets-encrypt [-h -t -d]"
+#				echo ""
+#				echo "    Obtain a certificate from Let's Encrypt and"
+#				echo "    automatically keep it up to date."
+#				echo ""
+#				echo "    -h: Display this help message"
+#				echo "    -t: Obtain a test certificate. This is a valid Let's"
+#				echo "        Encrypt certificate, but is not signed by a"
+#				echo "        recognized CA, so browsers will show a warning."
+#				echo "    -d: Dry run: don't actually obtain/install"
+#				echo "        certificates from Let's Encrypt, but make sure"
+#				echo "        it's possible."
+#				exit 0
+#				;;
+#			\?)
+#				echo "Invalid option: -$OPTARG" >&2
+#				exit 1
+#				;;
+#		esac
+#	done
 
-	echo "In order for Let's Encrypt to verify that you actually own the"
-	echo "domain(s) for which you're requesting a certificate, there are a"
-	echo "number of requirements of which you need to be aware:"
-	echo ""
+#	echo "In order for Let's Encrypt to verify that you actually own the"
+#	echo "domain(s) for which you're requesting a certificate, there are a"
+#	echo "number of requirements of which you need to be aware:"
+#	echo ""
+#
+#	echo "1. In order to register with the Let's Encrypt ACME server, you must"
+#	echo "   agree to the currently-in-effect Subscriber Agreement located"
+#	echo "   here:"
+#	echo ""
+#	echo "       https://letsencrypt.org/repository/"
+#	echo ""
+#	echo "   By continuing to use this tool you agree to these terms. Please"
+#	echo "   cancel now if otherwise."
+#	echo ""
+#
+#	echo "2. You must have the domain name(s) for which you want certificates"
+#	echo "   pointing at the external IP address of this machine."
+#	echo ""
+#
+#	echo "3. Both ports 80 and 443 on the external IP address of this machine"
+#	echo "   must point to this machine (e.g. port forwarding might need to be"
+#	echo "   setup on your router)."
+#	echo ""
 
-	echo "1. In order to register with the Let's Encrypt ACME server, you must"
-	echo "   agree to the currently-in-effect Subscriber Agreement located"
-	echo "   here:"
-	echo ""
-	echo "       https://letsencrypt.org/repository/"
-	echo ""
-	echo "   By continuing to use this tool you agree to these terms. Please"
-	echo "   cancel now if otherwise."
-	echo ""
+#	#while true; do
+#		printf "Have you met these requirements? (y/n) "
+#		read -r answer
+#		case $answer in
+#			[Yy]* ) break;;
+#			[Nn]* ) exit;;
+#			* ) echo "Please answer yes or no.";;
+#		esac
+#	done
 
-	echo "2. You must have the domain name(s) for which you want certificates"
-	echo "   pointing at the external IP address of this machine."
-	echo ""
+#	printf "Please enter an email address (for urgent notices or key recovery): "
+#	read -r email
 
-	echo "3. Both ports 80 and 443 on the external IP address of this machine"
-	echo "   must point to this machine (e.g. port forwarding might need to be"
-	echo "   setup on your router)."
-	echo ""
+#	domains=""
+#	printf "Please enter your domain name(s) (space-separated): "
+#	read -r answer
+#	for domain in $answer; do
+#		domains="$domains -d $domain"
+#	done
 
-	while true; do
-		printf "Have you met these requirements? (y/n) "
-		read -r answer
-		case $answer in
-			[Yy]* ) break;;
-			[Nn]* ) exit;;
-			* ) echo "Please answer yes or no.";;
-		esac
-	done
-
-	printf "Please enter an email address (for urgent notices or key recovery): "
-	read -r email
-
-	domains=""
-	printf "Please enter your domain name(s) (space-separated): "
-	read -r answer
-	for domain in $answer; do
+  mail=$1
+	shift
+  domains=""
+  for domain in "$@";
+	do
 		domains="$domains -d $domain"
 	done
+
 
 	printf "Attempting to obtain certificates... "
 	# Building CLI commands, so we don't WANT to quote some of these (they need
